### PR TITLE
Fix: #58 persistence service creates folder when saving

### LINKED ISSUE #58: The persistence service should create the folder if it doesn't exist
If the folder `testRuns` does not exist, the service should create it when saving a test run

### PR DESCRIPTION
**Pull request by alixpeigue**
When you call TestRunPersistenceService.save(...), it now creates the testRuns folder if it does not exist.

Closes #58

### CODE REVIEW

**Review by SetiQyu — APPROVED** [review]
Looks good to me!

File: src/main/java/app/ciserver/TestRunPersistenceService.java [hunk 1]
```diff
@@ -88,7 +101,10 @@ public List<TestRunModel> loadAll() {
 	 * @return true if the test run was saved successfully, false otherwise
 	 */
 	public boolean save(TestRunModel testRun) {
-		String filename = "testRuns/" + testRun.commitSHA() + ".json";
+		if (!createFolder()) {
```
Comment (AdamFR00) [inline src/main/java/app/ciserver/TestRunPersistenceService.java:104]: If you want this if statement the createFolder method needs a way to return false. The current version only returns true or throws an exception.

**Review by AdamFR00 — CHANGES_REQUESTED** [review]
Looks good. Please take a look at the comment.
